fix(core-ticket): Add dispatch_weblink field to core ticket plugin
When using the core ticket plugin, we're getting the error
`TypeError: DispatchTicketPlugin.update() got an unexpected keyword argument 'dispatch_weblink'`
This field was added for the Jira ticket plugin but never added to the
core plugin. Since the plugin returns no matter the arguments, I've simply added the field.