Fix Docker build directory visibility (#37)
* Fix Docker build directory visibility

The project Dockerfile lives in a `./docker` directory, but references
files hosted in the root directory, namely:

- `.nvmrc`
- `setup.py`

Dockerfiles can only reference files in the same folder as the build
context. This results in build errors reported in
https://github.com/Netflix/dispatch-docker/issues/2 and initially
addressed in https://github.com/Netflix/dispatch-docker/pull/1

```
ERROR: Service 'web' failed to build: COPY failed: stat
/var/lib/docker/tmp/docker-builder448268992/.nvmrc: no such file or
directory
```

This is a simple fix to move the Dockerfile into a reasonable scope via
symlink. However, open source contributors cannot build the image
locally since the build steps appear rely on access to resources on
Netflix internal network.

* Update installation.md

Co-authored-by: kevgliss <kevgliss@gmail.com>